"""FireSim environment setup."""

import os
import subprocess


def setup_firesim_env() -> dict:
    """Setup FireSim env vars + SSH agent. Returns env dict for subprocess."""
    env = os.environ.copy()
    env["FIRESIM_SOURCED"] = "1"  # For firesim Python CLI
    env["FIRESIM_ENV_SOURCED"] = "1"  # For firesim Makefile
    env["FIRESIM_RUNFARM_PREFIX"] = ""

    # Create minimal env.sh for firesim if it doesn't exist
    firesim_dir = os.path.join(
        os.environ.get("HOME", "/home/mio"),
        "Code/buckyball/arch/thirdparty/chipyard/sims/firesim"
    )
    env_sh = os.path.join(firesim_dir, "env.sh")
    if not os.path.exists(env_sh):
        riscv_path = env.get("RISCV", "/home/mio/Code/buckyball/result")
        with open(env_sh, "w") as f:
            f.write(f"""#!/usr/bin/env bash
# Minimal env.sh for FireSim (auto-generated by firesim_env.py)

export FIRESIM_ENV_SOURCED=1
export FS_DIR="{firesim_dir}"
export RISCV="{riscv_path}"
""")

    # Setup SSH agent for localhost FPGA enumeration
    key = os.path.expanduser("~/.ssh/firesim.pem")
    if os.path.exists(key) and "firesim.pem" not in subprocess.run(
        ["ssh-add", "-l"], capture_output=True, text=True
    ).stdout:
        if not env.get("SSH_AUTH_SOCK"):
            for line in subprocess.run(
                ["ssh-agent", "-s"], capture_output=True, text=True
            ).stdout.splitlines():
                if "=" in line:
                    k, v = line.split("=", 1)
                    env[k] = v.split(";", 1)[0]
        subprocess.run(["ssh-add", key], env=env, capture_output=True)

    return env

