# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x10\x62uckyball.config\"_\n\x0eModelParameter\x12\x11\n\x07integer\x18\x01 \x01(\x12H\x00\x12\x0e\n\x04real\x18\x02 \x01(\x01H\x00\x12\x0e\n\x04text\x18\x03 \x01(\tH\x00\x12\x11\n\x07\x62oolean\x18\x04 \x01(\x08H\x00\x42\x07\n\x05value\"\xc4\x01\n\x0bModelConfig\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x41\n\nparameters\x18\x03 \x03(\x0b\x32-.buckyball.config.ModelConfig.ParametersEntry\x1aS\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .buckyball.config.ModelParameter:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELCONFIG_PARAMETERSENTRY']._loaded_options = None
  _globals['_MODELCONFIG_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_MODELPARAMETER']._serialized_start=33
  _globals['_MODELPARAMETER']._serialized_end=128
  _globals['_MODELCONFIG']._serialized_start=131
  _globals['_MODELCONFIG']._serialized_end=327
  _globals['_MODELCONFIG_PARAMETERSENTRY']._serialized_start=244
  _globals['_MODELCONFIG_PARAMETERSENTRY']._serialized_end=327
# @@protoc_insertion_point(module_scope)
